//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModuleMaster
    {
        public ModuleMaster()
        {
            this.UserModuleMappingMasters = new HashSet<UserModuleMappingMaster>();
        }
    
        public int ModuleId { get; set; }
        public string ModuleName { get; set; }
        public string Description { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDelete { get; set; }
    
        public virtual ICollection<UserModuleMappingMaster> UserModuleMappingMasters { get; set; }
    }
}
