//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserModuleMappingMaster
    {
        public int UserModuleMappingId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> ModuleId { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual ModuleMaster ModuleMaster { get; set; }
        public virtual UserMaster UserMaster { get; set; }
    }
}
