//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserMaster
    {
        public UserMaster()
        {
            this.UserModuleMappingMasters = new HashSet<UserModuleMappingMaster>();
        }
    
        public int UserId { get; set; }
        public string UserFirstName { get; set; }
        public string UserMiddleName { get; set; }
        public string UserLastName { get; set; }
        public string UserEmail { get; set; }
        public string UserMobile { get; set; }
        public string Address { get; set; }
        public string UserPassword { get; set; }
        public string UniqueUserId { get; set; }
        public Nullable<int> RoleId { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
    
        public virtual RoleMaster RoleMaster { get; set; }
        public virtual ICollection<UserModuleMappingMaster> UserModuleMappingMasters { get; set; }
    }
}
